### ISSUE TITLE
README.md only works for a new installation of R

### ISSUE THREAD

**Issue by nathaneastwood** [MangoTheCat/pkgsnap#7] opened 2015-12-09 15:36 UTC
Following the example in `README.md`, it installs all packages you currently have installed on your system. This is because `snap()` is not explicit in where it should obtain the packages from by default, i.e. the user does not give it `lib.loc` for the `installed.packages()` function. Instead it uses the default `NULL` for all known trees (from `?installed.packages`). Possibly a roxygen `@param` tag is needed in the `?snap` helpfile to explain the `recommended` parameter?

**Comment by gaborcsardi** [comment] 2015-12-09 15:44
Hmmm. So as I understand the problem is that `snap` does not have a (maybe compulsory?) `lib.loc` argument? 

Yes, I think this would be reasonable.

The thing is, the library directories are a bit messed up in R, and we need to think about this a bit more, to see how we could handle the common use cases easily.

Right now the assumption is that you have all `base` and `recommended` packages in some _system_ library directory and everything else in your _project_ library directory. Then `pkgsnap` works I guess. (Apart from the question of where to put `pkgsnap` itself.) But I agree that many people don't use this setup, and they need something more flexible.

Does this make sense?

**Comment by nathaneastwood** [comment] 2015-12-09 15:48
Indeed, I believe it needs a `lib.loc` argument for more flexibility when working outside of projects, though your argument is logical.

**Comment by gaborcsardi** [comment] 2015-12-09 15:52
Yes, I think `lib.loc` is reasonable. The default could be all directories in `.libPaths()`, maybe?

EDIT: or just `NULL`, which means the default in `installed.packages` I guess.

**Comment by nathaneastwood** [comment] 2015-12-09 15:56
Yes, I would suggest that `NULL` makes the most sense to match the behaviour of the default `installed.packages()`. 

Also, I am not sure why the `@param` tag for `recommended` in `snap` is not working? I have recreated it on my machine and ran `devtools::document()` followed by `devtools::build()` and the tag is there when I look at `?snap`, but it is not available in the GitHub build?

**Comment by gaborcsardi** [comment] 2015-12-09 16:00
As for `@param` I just probably forgot to run `document()` on the code before pushing it to GH.

**Comment by dougmet** [comment] 2015-12-09 16:30
There have been a few recent commits that should have picked up the recommended `@param`. Might be worth updating to the latest commit (ae0cec58 as I write).

**Comment by nathaneastwood** [comment] 2015-12-09 16:50
@dougmet yes I eventuallu noticed when I first tried to make a pull request. I've submitted a new one now - it's very straight forward! This is my first time submitting a pull request on a public repo so hopefully I've done it correctly...

**Comment by gaborcsardi** [comment] 2015-12-14 15:32
I think we can close this now. Reopen if you don't agree.

**Closed as completed by gaborcsardi** 2015-12-14 15:32 UTC
